### ISSUE TITLE
Enhance Landing Page

### ISSUE THREAD

**Issue by mmuhamadamirzaidi-work** [mmuhamadamirzaidi-work/landing-page#1]
I need help to enhance landing page to put 2 image (globe.png) at the left and right side like in the ss-need-to-be.png image, and when open through mobile apps, the image will disappear.

ss.png **(Original)**

ss-need-to-be.png **(How it should look like)**

Can check the image in the repository, and let me know here if there're any questions or detail brief needed.

Thanks and lot of love from me ❤️

**Comment by devTam** [comment]
assign this to me

**Comment by mmuhamadamirzaidi-work** [comment]
Sure @devTam :D

**Comment by mmuhamadamirzaidi-work** [comment]
Everything okayy @devTam ? :D

**Comment by devTam** [comment]
Everything is fine. Working on it now

**Comment by mmuhamadamirzaidi-work** [comment]
Will check on it @devTam :D

**Comment by devTam** [comment]
you can close this now since its fixed

**Comment by mmuhamadamirzaidi** [comment]
Will close it tomorrow after checking it. Thanks @devTam :D
